---
- name: Take volume snapshot in AWS
  hosts: all
  become: yes
  
  tasks: 
#    - name: Add repository
#      yum_repository:
#        name: epel
#        description: EPEL YUM repo
#        baseurl: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
#        enabled: yes
    - name: Add repo
      yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm state=present
      
#    - name: Install PIP needed for BOTO
#      yum: name=pip update_cache=yes state=present
        
    - name: Install BOTO
      pip: name=boto3 state:latest
      
#    - name: Take volume snapshot in AWS
#      ec2_snapshot:
#        volume_id: vol-07de2f7eeede26afd
#        description: snapshot of MSURHEL1 taken 11/28/2016 08:12
        
        
    - name: Snapshot the instance.
      ec2_snapshot:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        instance_id: i-0080a6f836de932ba
        volume_id: vol-07de2f7eeede26afd
        description: awsbackup snapshot taken on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}

       
