---
- name: Take volume snapshot in AWS
  hosts: all
  become: yes
  
  tasks: 
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        enabled: yes
  
    - name: Install PIP needed for BOTO
      yum: name=pip state=present
      
    - easy_install: name=pip state=latest
  
    - name: Install BOTO
      pip: name=boto3
      
    - name: Take volume snapshot in AWS
      ec2_snapshot:
        volume_id: vol-07de2f7eeede26afd
        description: snapshot of MSURHEL1 taken 11/28/2016 08:12
       
