---
- name: Take volume snapshot in AWS
  hosts: all

  tasks:        
    - name: Install python 2.0
      win_chocolatey:
        name: python2
    - name: Install pip
      win_chocolatey:
        name: pip
    - name: Create Directory
      win_file: path=C:\AWSMsi\ state=directory
      
    - name: Pull MSI file
      win_get_url: 
        url: http://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi
        dest: 'C:\AWSMsi\AWSToolsAndSDKForNet.msi'
        skip_certificate_validation: true
          
    - name: Runs MSI file
      win_msi:
        path: C:\AWSMsi\AWSToolsAndSDKForNet.msi
        wait: true
          
    - name: Snapshot the instance.
      ec2_snapshot:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        volume_id: vol-0fd39a57fccae6e2a
        profile: no
        description: awsbackup snapshot taken on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}
