---
- name: Take volume snapshot in AWS
  hosts: all
  become: yes
  
  tasks: 
#    - name: Add repository
#      yum_repository:
#        name: epel
#        description: EPEL YUM repo
#        baseurl: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
#        enabled: yes
    - name: Add repo
      yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm state=present
      
#    - name: Install PIP needed for BOTO
#      yum: name=pip update_cache=yes state=present
        
    - name: Install BOTO
      pip: name=boto3
      
    - name: Take volume snapshot in AWS
      ec2_snapshot:
        volume_id: vol-07de2f7eeede26afd
        description: snapshot of MSURHEL1 taken 11/28/2016 08:12
       
