---
- name: Take volume snapshot in AWS
  hosts: all

  tasks:
    - name: unInstall python
      win_chocolatey:
        name: python
        state: absent
        
    - name: Install python 2.0
      win_chocolatey:
        name: python2

    - name: Snapshot the instance.
      ec2_snapshot:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        volume_id: vol-0fd39a57fccae6e2a
        description: awsbackup snapshot taken on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}
