---
- name: Rollback to a previous snapshot
  hosts: localhost
  become: yes
    
  tasks:
    
   - name: Stop the instance
     ec2:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        instance_ids: i-04cc3194d864eb0c0
        state: stopped 
        wait: yes
   - name: Detach the old volume
     ec2_vol:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        id: vol-0fd39a57fccae6e2a
        instance: None 
#        register: detach_vol 

   - name: Creating a Volume from a snapshot 
     ec2_vol:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        snapshot: snap-013545aeff31bc4cd
        region: us-east-1
        volume_type: gp2
        instance: i-04cc3194d864eb0c0
        device_name: /dev/sda1
#        volume_size: 60
     register: ec2_vol 
#        tags: attach 

   - name: Attach the Created volume to an instance 
     ec2_vol: 
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        instance: i-04cc3194d864eb0c0
        id: "{{ ec2_vol.volume_id }}"
        device_name: /dev/sda1
    
   - name: Start the instance
     ec2:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        instance_ids: i-04cc3194d864eb0c0
        state: running     
