---
- name: Rollback to a previous snapshot
  hosts: linux2
  become: yes
    
  tasks:
    
   - name: Stop the instance
     ec2:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        instance_ids: i-0080a6f836de932ba
        state: stopped    
   - name: Wait for stopped
     wait_timeout: 60
   - name: Detach the old volume
     ec2_vol:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        id: vol-07de2f7eeede26afd
        instance: None 
#        register: detach_vol 

   - name: Creating a Volume from a snapshot 
     ec2_vol:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        snapshot: snap-0533d3646be12fb57
        region: us-east-1
        volume_type: gp2
        instance: i-0080a6f836de932ba
        device_name: /dev/sda1
#        volume_size: 60
     register: ec2_vol 
#        tags: attach 

   - name: Attach the Created volume to an instance 
     ec2_vol: 
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        instance: i-0080a6f836de932ba
        id: "{{ ec2_vol.volume_id }}"
        device_name: /dev/sda1
    
   - name: Start the instance
     ec2:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        instance_ids: i-0080a6f836de932ba
        state: running     
