---
- name: Rollback to a previous snapshot
  hosts: all
  become: yes
    
  tasks:
    
#    - name: Detach the old volume 
#      ec2_vol:
#        aws_secret_key: "{{pkey}}"
#        aws_access_key: "{{akey}}"
#        region: us-east-1
#        id: vol-07de2f7eeede26afd
#        instance: None 
#        register: detach_vol 

    - name: Creating a Volume from a snapshot 
      ec2_vol:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        snapshot: snap-0533d3646be12fb57
        region: us-east-1
        volume_size: 60 
        register: new_ec2_vol 
#        tags: attach 

    - name: Attach the Created volume to an instance 
      ec2_vol: 
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        instance: i-0080a6f836de932ba
        id: new_ec2_vol
        device_name: /dev/sda1 
        delete_on_termination: yes
    
    - name: Stop the instance
      ec2:
        aws_secret_key: "{{pkey}}"
        aws_access_key: "{{akey}}"
        region: us-east-1
        instance_ids: i-0080a6f836de932ba
        state: stopped
