 ---
 - name: Test
  hosts: localhost
  become: yes
    
  tasks:
    - name: Snapshot the instance.
      ec2_snapshot:
        region: us-east-1
#        instance_id: i-0080a6f836de932ba
        volume_id: vol-07de2f7eeede26afd
        description: awsbackup snapshot taken on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}
